'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const places=[{"id":"current","name":"Current location · KTH Entré","sub":"Drottning Kristinas väg 4","lat":59.3470612,"lng":18.0720447},{"id":"home","name":"Home · Odenplan","sub":"Frequent place","lat":59.3427,"lng":18.0497},{"id":"work","name":"Work · Stockholm Central","sub":"Frequent place","lat":59.3302,"lng":18.0582},{"id":"museum","name":"Vasa Museum","sub":"Suggested for you · Weekend exploring","lat":59.3281,"lng":18.0901},{"id":"east","name":"Stockholm City Hall","sub":"Suggested for you · Waterfront landmark","lat":59.3282,"lng":18.055},{"id":"palace","name":"Royal Palace","sub":"Historic landmark · Old Town","lat":59.3267,"lng":18.0734}];
const preferences={fast:'Fastest',short:'Shortest',calm:'Less traffic',scenic:'Landmarks',nature:'Nature',random:'Surprise me',all:'All'};
const state={stage:'home',version:new URLSearchParams(location.search).get('version')==='B'?'B':'A',from:places[0],to:null,departure:'',mode:null,pref:'fast',routes:[],selected:0,detail:false,busy:false,error:'',cached:false,nav:null,searchTarget:null,query:'',follow:true};
let routeSeq=0,toastTimer;const cache=new Map();
const map=L.map('map',{zoomControl:false}).setView([59.3470612,18.0720447],13);
const tiles=protomapsL.leafletLayer({url:'stockholm.pmtiles',flavor:'light',lang:'en',attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> · <a href="https://protomaps.com" target="_blank" rel="noopener">Protomaps</a>'}).addTo(map);
const marker=L.marker([places[0].lat,places[0].lng],{icon:positionIcon(45),zIndexOffset:1000}).addTo(map);
const lines=L.layerGroup().addTo(map),pins=L.layerGroup().addTo(map);
map.on('dragstart',()=>{state.follow=false;$('#locate').title='Resume location tracking'});
function positionIcon(angle){return L.divIcon({className:'position-icon',html:'<div class="position-wrap" style="transform:rotate('+angle+'deg)"><div class="position-dot"></div></div>',iconSize:[30,30],iconAnchor:[15,15]})}
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',3200)}
function departureLabel(){return state.departure?new Date(state.departure).toLocaleString('en-GB',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'Leave now'}
function peak(){const hour=state.departure?new Date(state.departure).getHours():new Date().getHours();return (hour>=7&&hour<10)||(hour>=16&&hour<19)}
function minutes(r){return Math.max(1,Math.round(r.duration*(peak()?r.peakFactor:1.08)/60))}
function eta(min){return new Date((state.departure?new Date(state.departure).getTime():Date.now())+min*60000).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}
function btn(text,action,cls=''){return '<button class="'+cls+'" data-action="'+action+'">'+text+'</button>'}
function placeButton(p){return '<button class="place" data-place="'+p.id+'"><span class="icon">'+(p.id==='current'?'◎':p.id==='home'?'⌂':'↗')+'</span><span><b>'+p.name+'</b><small class="sub">'+p.sub+'</small></span></button>'}
function handle(){return '<div class="handle"></div>'}
function setStage(stage){state.stage=stage;state.error='';render()}
function render(){
 for(const v of ['A','B']){$('#version'+v).classList.toggle('active',state.version===v);$('#version'+v).setAttribute('aria-pressed',state.version===v)}
 $('#versionDescription').textContent=state.version==='A'?'Choose Efficiency or Explore, then choose a route preference.':'Compare routes, then filter by priority or feature.';
 for(const id of ['pause','traffic','arrive'])$('#'+id).disabled=state.stage!=='nav';$('#pause').textContent=state.nav?.paused?'Resume driving':'Pause driving';
 $('#labStatus').textContent='Status: '+({home:'Map home',setup:'Trip setup',routes:'Route selection',nav:'Navigation',arrived:'Arrived'}[state.stage]||state.stage);
 $('#top').innerHTML=state.stage==='home'?btn('⌕ Where to?','destination','searchhome'):state.stage==='nav'?navTop():state.stage==='arrived'?'':'<div class="floating"><div class="row"><button class="textbtn" data-action="back" aria-label="Back">‹</button><div class="grow"><button class="field" data-action="origin"><span class="label">From</span><strong>'+esc(state.from.name)+'</strong></button><button class="field" data-action="destination"><span class="label">To</span><strong>'+esc(state.to?.name||'Choose destination')+'</strong></button></div><button class="textbtn" data-action="swap" aria-label="Swap start and destination">⇅</button></div><button class="field" data-action="time"><span>◷</span><strong>'+departureLabel()+'</strong><span class="sub">Edit</span></button></div>';
 let content='';
 if(state.stage==='home')content='<h2>Start a trip</h2><p>Where to?</p>'+placeButton(places[1])+placeButton(places[2])+placeButton(places[4])+'<div class="map-status">North-up map</div>';
 if(state.stage==='setup')content='<h2>Plan your trip</h2><p>'+(state.to?'Confirm your starting point and departure time.':'Choose a destination first.')+'</p><div class="notice">'+(state.departure?'Departure time selected.':'Start from your current location and leave now.')+'</div>'+(state.error?'<div class="notice error" role="alert">'+esc(state.error)+'</div>':'')+'<button class="primary" data-action="plan" '+(!state.to||state.busy?'disabled':'')+'>Find routes</button>';
 if(state.stage==='routes')content=routesContent();
 if(state.stage==='nav')content=navContent();
 if(state.stage==='arrived')content='<h2>You have arrived</h2><p>'+esc(state.to.name)+'</p><div class="notice">You have reached your destination.</div>'+btn('Done — back to home','finish','primary')+btn('Compare routes again','again','secondary');
 $('#sheet').innerHTML=handle()+content;$('#sheet').style.maxHeight=state.stage==='nav'?'43%':'56%';$('#top').style.display=state.searchTarget?'none':'';
}
function routesContent(){
 if(state.busy)return '<h2>Finding road routes…</h2><p role="status">Connecting to the map service, please wait.</p>'+btn('Cancel','cancelPlan','secondary');
 if(state.error)return '<h2>Unable to plan a route</h2><div class="notice error" role="alert">'+esc(state.error)+'</div>'+btn('Try again','plan','primary')+btn('Edit trip','setup','secondary');
 const mode=state.version==='A';
 if(mode&&!state.mode)return '<h2>How would you like to drive?</h2><button class="modecard" data-mode="efficiency"><b>Efficiency</b><span>Faster, shorter, or less traffic</span></button><button class="modecard" data-mode="explore"><b>Explore</b><span>Discover landmarks, or enjoy nature along the way</span></button><div class="map-status">Found '+state.routes.length+' road routes · choose your driving style</div>';
 const prefs=mode?(state.mode==='efficiency'?['fast','short','calm']:['scenic','nature','random']):['fast','short','calm','scenic','nature','all'];
 const ids=visibleRoutes(),selected=state.routes[state.selected];
 return '<div class="row between"><h2>'+(mode?(state.mode==='efficiency'?'Efficiency':'Explore'):'Choose a route')+'</h2>'+(mode?btn('Change mode','modes','textbtn'):'')+'</div><div class="chips">'+prefs.map(p=>'<button '+(['nature','scenic'].includes(p)&&!state.routes.some(r=>r.kind===p)?'disabled ':'')+'data-pref="'+p+'" aria-pressed="'+(state.pref===p)+'" class="'+(state.pref===p?'active':'')+'">'+preferences[p]+'</button>').join('')+'</div><div class="route-list">'+(ids.map(i=>routeCard(state.routes[i],i)).join('')||'<p>No routes match your preferences.</p>')+'</div>'+(!ids.length?btn('Clear filters','clear','secondary'):'')+(mode?btn(state.detail?'Hide alternatives':'View alternatives','alternatives','textbtn'):'')+(state.showDetails&&selected?'<div class="detail">'+esc(selected.description)+'<br>Estimated time '+minutes(selected)+' min.<br>'+selected.steps.slice(0,4).map(s=>esc(s.name||'Unnamed road')).join(' → ')+'</div>':'')+'<div class="row between"><span class="map-status">'+'Arrival estimates'+'</span>'+(ids.length?btn(state.showDetails?'Hide':'Details','details','textbtn'):'')+'</div>'+(ids.length?btn('Start navigation','start','primary'):'');
}
function sortedIndices(pref){return state.routes.map((r,i)=>i).sort((a,b)=>pref==='short'?state.routes[a].distance-state.routes[b].distance:pref==='calm'?state.routes[a].traffic-state.routes[b].traffic:minutes(state.routes[a])-minutes(state.routes[b]))}
function visibleRoutes(){if(state.version==='A')return state.detail?sortedIndices(state.pref):(state.routes.length?[state.selected]:[]);if(['nature','scenic'].includes(state.pref))return state.routes.map((r,i)=>i).filter(i=>state.routes[i].kind===state.pref);return sortedIndices(state.pref)}
function routeCard(r,i){const tags=[];if(i===sortedIndices('fast')[0])tags.push('Fastest');if(i===sortedIndices('short')[0])tags.push('Shortest');if(r.kind==='nature')tags.push('Nature');if(r.kind==='scenic')tags.push('Landmarks');const m=minutes(r);return '<button class="routecard '+(i===state.selected?'selected':'')+'" data-route="'+i+'" aria-pressed="'+(i===state.selected)+'"><div class="row between"><span><strong>'+m+'</strong> min</span><span class="sub">'+(r.distance/1000).toFixed(1)+' km · '+eta(m)+' arrival</span></div><div class="row between"><span>'+r.label+'</span><span class="tag">'+(tags.join(' · ')||'Alternative')+'</span></div><p>'+(peak()&&r.traffic>1?'Heavier traffic expected':'Lighter traffic expected')+(r.kind!=='direct'?' · via a stop':'')+'</p></button>'}
function selectPref(pref){state.pref=pref;state.detail=false;state.showDetails=false;if(['nature','scenic'].includes(pref)&&!state.routes.some(r=>r.kind===pref)){state.pref='fast';toast('This route feature is unavailable, showing other routes')}let ids=sortedIndices(state.pref);if(pref==='nature'||pref==='scenic')ids=ids.filter(i=>state.routes[i].kind===pref);if(pref==='random')state.selected=Math.floor(Math.random()*state.routes.length);else if(ids.length)state.selected=ids[0];drawRoutes(false);render()}
function drawRoutes(fit=true){lines.clearLayers();pins.clearLayers();if(!state.to)return;for(const [p,text,cls] of [[state.from,'S',''],[state.to,'D','end']])L.marker([p.lat,p.lng],{icon:L.divIcon({className:'',html:'<div class="pin '+cls+'">'+text+'</div>',iconSize:[27,27],iconAnchor:[13,13]})}).addTo(pins);
 const allowed=state.stage==='nav'?[state.selected]:state.version==='A'&&!state.mode?[]:visibleRoutes();
 for(const i of allowed.filter(i=>i!==state.selected).concat(allowed.includes(state.selected)?[state.selected]:[])){const r=state.routes[i];if(!r)continue;const layer=L.geoJSON(r.geometry,{style:{color:i===state.selected?'#2864eb':'#91a1b8',weight:i===state.selected?6:4,opacity:.95}}).addTo(lines);layer.on('click',()=>{if(state.stage!=='routes'||state.busy)return;state.selected=i;state.showDetails=false;drawRoutes(false);render()})}
 if(fit){const coords=state.routes[state.selected]?.geometry.coordinates;const bounds=coords?.length?L.latLngBounds(coords.map(c=>[c[1],c[0]])):L.latLngBounds([[state.from.lat,state.from.lng],[state.to.lat,state.to.lng]]);map.fitBounds(bounds,{paddingTopLeft:[30,190],paddingBottomRight:[30,$('#sheet').offsetHeight+50],maxZoom:14,animate:false})}
}
async function requestRoute(points,alternatives=false){const coords=points.map(p=>p.lng+','+p.lat).join(';');const response=await fetch('https://router.project-osrm.org/route/v1/driving/'+coords+'?overview=full&geometries=geojson&steps=true&alternatives='+alternatives,{signal:AbortSignal.timeout(16000)});if(!response.ok)throw Error('The routing service is unavailable');const data=await response.json();if(data.code!=='Ok'||!data.routes?.length)throw Error('No driving route was found');return data.routes}
async function plan(){if(!state.to)return;if(state.from.lat===state.to.lat&&state.from.lng===state.to.lng){state.stage='setup';state.error='Your start and destination are the same, choose a different place.';render();return}const seq=++routeSeq;state.busy=true;state.error='';state.stage='routes';state.showDetails=false;lines.clearLayers();render();const key=state.from.id+'-'+state.to.id;let records=cache.get(key);state.cached=false;
 try{if(!records){const backup=await fetch('sample-routes.json').then(r=>r.ok?r.json():null).catch(()=>null);if(backup?.[key]){records=backup[key];state.cached=true;cache.set(key,records)}}if(!records){const requests=await Promise.allSettled([requestRoute([state.from,state.to],true),requestRoute([state.from,{lat:59.3398,lng:18.0726},state.to]),requestRoute([state.from,{lat:59.3354,lng:18.0732},state.to])]);if(seq!==routeSeq)return;records=[];const labels=['Direct route','Via Humlegården','Via Stureplan'];requests.forEach((result,index)=>{if(result.status==='fulfilled')result.value.slice(0,index?1:2).forEach((r,j)=>records.push({...r,kind:['direct','nature','scenic'][index],label:index===0&&j?'Alternative direct route':labels[index],description:index===0?'A direct route to your destination.':index===1?'Passes beside Humlegården.':'Passes through Stureplan.',traffic:index===0?3-j:index===1?1:2,peakFactor:index===0?1.55-j*.12:index===1?1.15:1.3,steps:r.legs.flatMap(l=>l.steps)}))});if(!records.length){const backup=await fetch('sample-routes.json').then(r=>r.ok?r.json():null).catch(()=>null);if(backup?.[key]){records=backup[key];state.cached=true}else throw Error('Cannot connect to the routing service. Check your connection, or try KTH Entré → Stockholm City Hall.')}cache.set(key,records)}if(seq!==routeSeq)return;state.routes=records;state.selected=0;state.busy=false;selectPref(state.pref);drawRoutes()}catch(e){if(seq!==routeSeq)return;state.busy=false;state.error=e.message;render()}
}
function openSearch(target){state.searchTarget=target;state.query='';$('#top').style.display='none';$('#modal').innerHTML='<div class="overlay"><div class="row between"><h2>'+(target==='from'?'Choose starting point':'Choose destination')+'</h2>'+btn('Cancel','closeSearch','textbtn')+'</div><input id="placeQuery" type="search" placeholder="Search places" aria-label="Search places" autocomplete="off"><div class="sub">Search by place name</div><div class="results" id="results"></div></div>';renderResults();$('#placeQuery').addEventListener('input',e=>{state.query=e.target.value;renderResults()});$('#placeQuery').focus()}
function renderResults(){const query=state.query.trim().toLowerCase();const matches=places.filter(p=>(p.name+' '+p.sub).toLowerCase().includes(query));$('#results').innerHTML=matches.length?(!query?'<h3>Current location / Frequent / Suggested</h3>':'')+matches.map(placeButton).join(''):'<p>No places found. Try KTH, Odenplan or City Hall.</p>'}
function closeModal(){state.searchTarget=null;$('#modal').innerHTML='';render()}
function choosePlace(id){const p=places.find(p=>p.id===id);if(!p)return;const target=state.searchTarget||'to';routeSeq++;state.busy=false;state[target]=p;state.routes=[];lines.clearLayers();state.stage='setup';closeModal();drawRoutes()}
function openTime(){const now=new Date();now.setMinutes(now.getMinutes()-now.getTimezoneOffset());const value=state.departure||now.toISOString().slice(0,16);$('#modal').innerHTML='<div class="overlay"><div class="row between"><h2>When are you leaving?</h2>'+btn('Cancel','closeSearch','textbtn')+'</div>'+btn('Leave now','now','secondary')+'<label for="departureTime">Choose a departure time</label><input id="departureTime" type="datetime-local" value="'+value+'">'+btn('Confirm time','saveTime','primary')+'</div>'}
function updateTime(value){if(value&&(!Number.isFinite(new Date(value).getTime())||new Date(value)<new Date(Date.now()-60000))){toast('Choose a departure time now or in the future');return}state.departure=value;closeModal();if(state.stage==='routes'&&state.routes.length){selectPref(state.pref);toast('Travel times updated')}else render()}
function dialog(title,body,buttons){$('#modal').innerHTML='<div class="modalshade"><div class="dialog" role="dialog" aria-modal="true" aria-label="'+title+'"><h2>'+title+'</h2><p>'+body+'</p>'+buttons+'</div></div>';$('#modal button')?.focus()}
function start(){if(!state.routes[state.selected])return;if(state.departure||state.from.id!=='current')dialog('Start navigation','Start from '+esc(state.from.name)+'. Departure: '+departureLabel()+'.',btn('Start navigation','confirmStart','primary')+btn('Back','closeSearch','secondary'));else beginNavigation()}
function distance(a,b){const lat=(a[1]+b[1])*Math.PI/360;return Math.hypot((b[0]-a[0])*111320*Math.cos(lat),(b[1]-a[1])*111320)}
function beginNavigation(){closeModal();const r=state.routes[state.selected],coords=r.geometry.coordinates,cumulative=[0];for(let i=1;i<coords.length;i++)cumulative.push(cumulative[i-1]+distance(coords[i-1],coords[i]));let d=0;const stepEnds=r.steps.map(s=>{d+=s.distance;return d});state.nav={distance:0,total:cumulative.at(-1),cumulative,coords,paused:false,stepEnds,traffic:false,origin:state.nav?.origin||state.from,extra:0};state.follow=true;state.stage='nav';drawRoutes(false);render();tick(0)}
function navTop(){const n=state.nav,r=state.routes[state.selected];if(!n||!r)return '';let index=n.stepEnds.findIndex(d=>d>=n.distance*r.distance/n.total);if(index<0)index=r.steps.length-1;const next=r.steps[Math.min(index+1,r.steps.length-1)],remaining=Math.max(0,n.stepEnds[index]-n.distance*r.distance/n.total),mod=next?.maneuver?.modifier||'';const instruction=next?.maneuver?.type==='arrive'?'Arrive at destination':next?.maneuver?.type==='roundabout'?'Enter the roundabout':mod==='uturn'?'Make a U-turn':mod.includes('left')?'Turn left':mod.includes('right')?'Turn right':'Continue ahead';return '<div class="floating navtop"><div class="row"><strong style="font-size:34px">'+(mod.includes('left')?'↰':mod.includes('right')?'↱':'↑')+'</strong><div><strong>'+(remaining>1000?(remaining/1000).toFixed(1)+' km':Math.round(remaining/10)*10+' m')+' '+instruction+'</strong><p>'+esc(next?.name||'Continue on the current road')+'</p></div></div><small style="color:#dce8ff">Navigation'+(n.paused?' · Paused':'')+'</small></div>'}
function navContent(){const n=state.nav,r=state.routes[state.selected],fraction=Math.max(0,1-n.distance/n.total),mins=Math.ceil(minutes(r)*fraction+n.extra);return (n.traffic?'<div class="notice"><b>Traffic ahead</b><br>This route will take an extra 5 min.<div class="row">'+btn('Keep route','keep','textbtn')+btn('Replan route','reroute','textbtn')+'</div></div>':'')+'<div class="navnumbers"><div><strong>'+mins+'</strong><small>min left</small></div><div><strong>'+(r.distance*fraction/1000).toFixed(1)+'</strong><small>km left</small></div><div><strong>'+eta(minutes(r)+n.extra)+'</strong><small>Arrival</small></div></div><div class="row">'+btn('Overview','overview','secondary')+btn('Exit navigation','exit','secondary')+'</div>'}
function tick(seconds){const n=state.nav;if(state.stage!=='nav'||!n||n.paused)return;const r=state.routes[state.selected];n.distance+=seconds*Number($('#speed').value)*n.total/((minutes(r)+n.extra)*60);if(n.distance>=n.total){arrive();return}let i=n.cumulative.findIndex(d=>d>=n.distance);i=Math.max(1,i);const a=n.coords[i-1],b=n.coords[i],t=(n.distance-n.cumulative[i-1])/(n.cumulative[i]-n.cumulative[i-1]||1);const pos=[a[1]+(b[1]-a[1])*t,a[0]+(b[0]-a[0])*t],bearing=Math.atan2((b[0]-a[0])*Math.cos(pos[0]*Math.PI/180),b[1]-a[1])*180/Math.PI;marker.setLatLng(pos).setIcon(positionIcon(bearing));if(state.follow){map.setView(pos,15,{animate:false});map.panBy([0,70],{animate:false})}$('#top').innerHTML=navTop();$('#sheet').innerHTML=handle()+navContent()}
function arrive(){if(!state.nav)return;marker.setLatLng([state.to.lat,state.to.lng]);map.setView([state.to.lat,state.to.lng],15);state.stage='arrived';$('#modal').innerHTML='';state.follow=false;render()}
function reset(){routeSeq++;Object.assign(state,{busy:false,stage:'home',from:places[0],to:null,departure:'',routes:[],mode:null,pref:'fast',nav:null,searchTarget:null,error:'',showDetails:false,detail:false});$('#modal').innerHTML='';lines.clearLayers();pins.clearLayers();marker.setLatLng([places[0].lat,places[0].lng]).setIcon(positionIcon(45));map.setView([59.3470612,18.0720447],13);render()}
const actions={destination:()=>openSearch('to'),origin:()=>openSearch('from'),closeSearch:closeModal,time:openTime,now:()=>updateTime(''),saveTime:()=>updateTime($('#departureTime').value),plan,setup:()=>setStage('setup'),back:()=>{routeSeq++;state.busy=false;if(state.stage==='routes')setStage('setup');else reset()},swap:()=>{if(!state.to)return;[state.from,state.to]=[state.to,state.from];state.routes=[];routeSeq++;state.busy=false;setStage('setup');drawRoutes()},cancelPlan:()=>{routeSeq++;state.busy=false;setStage('setup')},modes:()=>{state.mode=null;state.detail=false;render();drawRoutes(false)},alternatives:()=>{state.detail=!state.detail;render();drawRoutes(false)},details:()=>{state.showDetails=!state.showDetails;render()},clear:()=>selectPref('all'),start,confirmStart:beginNavigation,overview:()=>{state.follow=false;drawRoutes()},exit:()=>{state.nav.paused=true;render();dialog('End navigation?','Return to route selection. Your trip settings will be kept.',btn('End navigation','confirmExit','primary')+btn('Continue navigation','resume','secondary'))},resume:()=>{state.nav.paused=false;closeModal()},confirmExit:()=>{state.stage='routes';state.nav=null;marker.setLatLng([places[0].lat,places[0].lng]).setIcon(positionIcon(45));closeModal();drawRoutes()},finish:reset,again:()=>{state.nav=null;state.stage='routes';marker.setLatLng([places[0].lat,places[0].lng]);render();drawRoutes()},keep:()=>{state.nav.traffic=false;toast('Keeping your current route');render()},reroute:()=>{const pos=marker.getLatLng();state.from={id:'reroute-'+Date.now(),name:'Current driving position',lat:pos.lat,lng:pos.lng};state.departure='';state.nav.paused=true;state.mode='efficiency';state.pref='fast';plan()}};
document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el||el.disabled)return;if(el.dataset.action)actions[el.dataset.action]?.();else if(el.dataset.place)choosePlace(el.dataset.place);else if(el.dataset.mode){state.mode=el.dataset.mode;selectPref(state.mode==='efficiency'?'fast':'scenic');drawRoutes()}else if(el.dataset.pref)selectPref(el.dataset.pref);else if(el.dataset.route!==undefined){state.selected=Number(el.dataset.route);state.showDetails=false;drawRoutes(false);render()}});
for(const version of ['A','B'])$('#version'+version).onclick=()=>{if(state.stage==='nav'||state.stage==='arrived'){toast('Finish or exit navigation before switching versions');return}state.version=version;state.mode=null;state.detail=false;state.pref='fast';render();if(state.routes.length){selectPref('fast');drawRoutes()}};
$('#reset').onclick=reset;$('#pause').onclick=()=>{if(!state.nav)return;state.nav.paused=!state.nav.paused;render()};$('#traffic').onclick=()=>{if(state.nav.traffic||state.nav.extra){toast('Traffic has already been triggered for this trip');return}state.nav.traffic=true;state.nav.extra=5;render()};$('#arrive').onclick=arrive;$('#locate').onclick=()=>{state.follow=true;map.setView(marker.getLatLng(),15);toast('Centered on your location')};$('#north').onclick=()=>toast('The map stays north-up, the blue cone shows your heading');
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#modal').innerHTML){if(state.stage==='nav'&&state.nav.paused)actions.resume();else closeModal()}});
setInterval(()=>tick(.5),500);render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_navigation_trip',description:'Set a prototype journey using preset place IDs and display trip setup. Does not start driving.',inputSchema:{type:'object',properties:{from:{type:'string',enum:places.map(p=>p.id)},to:{type:'string',enum:places.map(p=>p.id)}},required:['from','to'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{const from=places.find(p=>p.id===input.from),to=places.find(p=>p.id===input.to);if(!from||!to||from.id===to.id)throw Error('Choose two different preset places');reset();state.from=from;state.to=to;setStage('setup');drawRoutes();return {stage:state.stage,from:from.name,to:to.name}}})).catch(()=>{})}catch{}}

